modLoader="javafml" 

loaderVersion="[25,)" 

issueTrackerURL="http://my.issue.tracker/"

[[mods]] 

modId="gamemenumodoption" 

version="1.1" 

displayName="GameMenuModOption" 

updateJSONURL="http://myurl.me/" 

displayURL="" 

logoFile="gamemenumodoption.png" 

credits=""

authors="MORIMORI0317" 

description='''
Thank you for downloading!

'''
