modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png" 
[[mods]]
modId="gamemenumodoption"
version="${file.jarVersion}" 
displayName="Game Menu Mod Option"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption" 
authors="MORIMORI0317" 
description="Thank you for downloading!"
