modLoader = "javafml"
loaderVersion = "[45,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuModOption/issues"

[[mods]]
modId = "gamemenumodoption"
version = "${file.jarVersion}"
displayName = "Game Menu Mod Option"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/GameMenuModOption/master/version_check.json"
logoFile = "logo.png"
authors = "MORIMORI0317"

description = '''
A mod that adds a mod option to the game menu
The ikisugi game menu mod...
'''

[[dependencies.gamemenumodoption]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"