modLoader="javafml"
loaderVersion="[38,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuModOption/issues"
[[mods]]
modId="gamemenumodoption"
version="${file.jarVersion}"
displayName="Game Menu Mod Option"
logoFile = "logo.png"
authors = "MORIMORI0317"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption"
description = "Thank you for downloading!\nA mod that adds a mod option to the game menu\nThe Ikisugi MOD..."

[modproperties.gamemenumodoption]
catalogueImageIcon = "logo.png"